name: Auto Deploy Hexo Blog
on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  deploy-hexo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: install Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g

      - name: cache Hexo
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: 安装依赖
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm install gulp-cli -g
          npm install --save

      - name: 生成静态文件
        run: |
          hexo clean
          hexo bangumi -u
          hexo generate
          gulp

      - name: deploy to github
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: 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
          repository-name: xuegqcto/xuegqcto.github.io
          branch: main
          folder: public
          commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"